# Creating NumPy Arrays
## Diving Into NumPy
*Curtis Miller*

In this notebook I demonstrate `ndarray` creation, along with saving and loading `ndarray`s.

Let's first create a vector of 1's

In [21]:
# A common idiom for importing NumPy
# (Could also use pylab, which imports all NumPy functions into global namespace)
import numpy as np

vec1 = np.ones((5))

print(vec1)

[1. 1. 1. 1. 1.]


In [22]:
vec1.dtype

dtype('float64')

Let's make these integers

In [24]:
vec1.dtype = np.int8
print(vec1)
vec1.dtype

[  0   0   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0
   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0   0   0
   0   0 -16  63]


dtype('int8')

**THIS WILL TEACH YOU TO BE CAREFUL WHEN CONVERTING `dtype`!!!**

Here would be a proper way to change `dtype`; by creating a new `ndarray`.

In [25]:
vec1 = np.ones((5))
vec1 = np.array(vec1, dtype = np.int8)
print(vec1)

[1 1 1 1 1]


In [26]:
print(vec1.dtype)

int8


In [27]:
vec1 = np.ones((5), dtype=np.int8)
vec1.dtype

dtype('int8')

In [28]:
print(vec1)

[1 1 1 1 1]


Let's make a "cube" of zeros. These will be `float64`.

In [33]:
arr1 = np.zeros((2, 2, 2), dtype=np.float64)
print(arr1)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


Let's make a 3x3 square matrix filled with random numbers.

In [34]:
mat1 = np.random.randn(3, 3)
print(mat1)

[[ 0.59882477 -1.01021491 -1.62815937]
 [-0.26580725 -3.02479566 -0.38034475]
 [ 0.04855343 -1.38090248 -1.0088584 ]]


We wrap this up by createing a 2x2 matrix of names we chose, and a 2x2x2 array containing numbers.

In [35]:
mat2 = np.array([["bob", "jane"], ["bill", "janet"]])
print(mat2)

[['bob' 'jane']
 ['bill' 'janet']]


In [36]:
mat2.dtype

dtype('<U5')

In [38]:
# Tuples can be used too
arr2 = np.array([[(1, 3, 5), (2, 4, 6)], [(1, np.nan, 1), (2, 2, 2)]])
# Despite the integers, nan forces the array to hold floats
print(arr2)

[[[ 1.  3.  5.]
  [ 2.  4.  6.]]

 [[ 1. nan  1.]
  [ 2.  2.  2.]]]


Let's say I want to copy `mat2`. Here's the first attempt:

In [39]:
mat2_cpy = mat2
print(mat2_cpy)

[['bob' 'jane']
 ['bill' 'janet']]


But watch what happens when I change an entry in `mat2`!

In [40]:
mat2[0,0] = 'liam'
print(mat2)

[['liam' 'jane']
 ['bill' 'janet']]


In [41]:
print(mat2_cpy)

[['liam' 'jane']
 ['bill' 'janet']]


If I want a *new* copy of `mat2`, I need to use the `copy()` method.

In [ ]:
mat2_cpy = mat2.copy()
mat2[0,0] = "amy"
print(mat2)

In [ ]:
print(mat2_cpy)

Let's save a file with some arrays. First, we should check to see our working directory.

In [ ]:
%pwd

Let's change directory.

In [ ]:
%cd "D:\Curtis\Documents\Jupyter Notebooks"

In [ ]:
%pwd

Let's save into a .npy file.

In [ ]:
np.save("arr1", arr1)

This is a binary file now in our working directory. We can load the array in this file using `load()`.

In [ ]:
arr1_new = np.load("arr1.npy")
print(arr1_new)

Let's create a CSV file that holds the information in `mat1`.

In [ ]:
np.savetxt("mat1.csv", mat1, delimiter=",")

Let's preview what the contents of `mat1.csv` look like.

In [ ]:
mat1file = open("mat1.csv", "r")
for l in mat1file:
    print(l)

In [ ]:
mat1file.close()

CSV files are common, simple means for storing data. You should be aware of how to use them. Here, we read the data in the file back into the session.

In [ ]:
mat1_new = np.loadtxt("mat1.csv", delimiter=",")
print(mat1_new)