## Running Through NumPy Data Types
*Curtis Miller*

In this notebook, we get a brief glance of NumPy objects and data types, and how to work with them.

Let's create arrays that use different data types and have different shapes.

In [1]:
import numpy as np

In [2]:
# Creating arrays of ones, but with differing dtypes
int_ones = np.ones((2, 2), dtype = np.int8)
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [3]:
int_ones.dtype

dtype('int8')

In [4]:
float_ones = np.ones((2, 2), dtype = np.float16)
float_ones

array([[1., 1.],
       [1., 1.]], dtype=float16)

In [5]:
float_ones.dtype

dtype('float16')

In [6]:
uint_ones = np.ones((2, 2), dtype = np.uint8)
uint_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [7]:
int_ones[1, 1] = -1
int_ones

array([[ 1,  1],
       [ 1, -1]], dtype=int8)

In [8]:
uint_ones[1, 1] = -1
uint_ones    # Surprise!

array([[  1,   1],
       [  1, 255]], dtype=uint8)

In [9]:
uint_ones.dtype = np.int8
uint_ones    # This works fine

array([[ 1,  1],
       [ 1, -1]], dtype=int8)

In [10]:
uint_ones.dtype = np.float16
uint_ones    # This, not so much

array([[1.53e-05],
       [     nan]], dtype=float16)

In [11]:
string_arr = np.array(["Sam", "Bill", "Gary"])
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U4')

In [12]:
string_arr[1] = "Waldo"
string_arr    # Cannot have strings longer than 4 characters

array(['Sam', 'Wald', 'Gary'], dtype='<U4')

In [13]:
string_arr = np.array(["Sam", "Bill", "Gary"], dtype = '<U16')
string_arr

array(['Sam', 'Bill', 'Gary'], dtype='<U16')

In [14]:
string_arr[1] = "Waldo"
string_arr

array(['Sam', 'Waldo', 'Gary'], dtype='<U16')

In [15]:
# Checking dtype
int_ones.dtype.type is np.int8

True

In [16]:
int_ones.dtype.type is np.float16

False

You can read more about `dtype`s in [NumPy's documentation](https://docs.scipy.org/doc/numpy-1.12.0/reference/arrays.dtypes.html).

### Special Values

Now let's look at generating special values, like `nan` or `inf`.

In [17]:
vec1 = np.array([1, -1, 0], dtype=np.float16)
vec2 = vec1 / 0
vec2

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([ inf, -inf,  nan], dtype=float16)

In [18]:
# Can we detect special values?
for i in vec2:
    print(i)
    print('------')
    print('Inf: ' + str(i == np.inf))
    print('-Inf: ' + str(i == -np.inf))
    print('NaN: ' + str(i == np.nan))    # Doesn't work!
    print('\n\n')

inf
------
Inf: True
-Inf: False
NaN: False



-inf
------
Inf: False
-Inf: True
NaN: False



nan
------
Inf: False
-Inf: False
NaN: False





In [19]:
# A better way
for i in vec2:
    print(i)
    print('------')
    print('Inf: ' + str(i == np.inf))
    print('-Inf: ' + str(i == -np.inf))
    print('NaN: ' + str(np.isnan(i)))    # Does work!
    print('\n\n')

inf
------
Inf: True
-Inf: False
NaN: False



-inf
------
Inf: False
-Inf: True
NaN: False



nan
------
Inf: False
-Inf: False
NaN: True





In [20]:
# Finite vs. infinite
for i in vec2:
    print(i)
    print('------')
    print('Is finite?: ' + str(np.isfinite(i)))
    print('Is infinite?: ' + str(np.isinf(i)))
    print('\n\n')

inf
------
Is finite?: False
Is infinite?: True



-inf
------
Is finite?: False
Is infinite?: True



nan
------
Is finite?: False
Is infinite?: False





In [ ]:
vec2[0] + 1

In [ ]:
vec2[0] * -1

In [ ]:
vec2[2] + 1

In [ ]:
2 ** vec2[1]

In [ ]:
2 ** vec2[0]

In [ ]:
np.inf - np.inf

In [ ]:
vec3 = np.array([999], dtype=np.float64)
vec3

In [ ]:
vec3[0] ** vec3[0]    # Huge; gives inf, even though this is finite

In [ ]:
vec4 = np.ones(5)
vec4[0] = np.nan
vec4

In [ ]:
np.sum(vec4)

In [ ]:
np.nansum(vec4)    # Ignores nans